title: HOLOQ
description: Intelligence Fractal Decompression Architecture
url: "https://holoq.ai"
baseurl: "/zip"
show_downloads: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
sass:
  sass_dir: _sass
  style: compressed

# Collections for different consciousness levels
collections:
  pages:
    output: true
    permalink: /:name

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: "default"