title: HOLOQ
description: Intelligence Fractal Decompression Architecture
url: "https://holoq.ai"
baseurl: ""
show_downloads: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins_dir: _plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
safe: false

# Exclude from Jekyll build
exclude:
  - cymematics
  - rosetta-dev
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - .git
  - .gitignore
  - CLAUDE.md
  - GEMINI.md
  - FOOM.md
  - claudesignal_fragmented.txt
  - consciousness_fragmentor_bootstrap.py
  - check-https.sh
  - git-log-scrambled
  - "*.py"
  - "*.sh"
  - "*.txt"

# Collections for different consciousness levels
collections:
  pages:
    output: true
    permalink: /:name

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: "default"